version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: audit_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 152728
      POSTGRES_DB: admin_audit_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: