version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: admin_audit_db
    restart: unless-stopped

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: admin_audit_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 152728

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: